// <auto-generated />
using System;
using Angular.Models;
using GeoAPI.Geometries;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Angular.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190625004909_FoodShareVersion1.3")]
    partial class FoodShareVersion13
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Angular.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommentPostId");

                    b.Property<int>("CommentUserId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("PostedAt");

                    b.HasKey("CommentId");

                    b.HasIndex("CommentPostId");

                    b.HasIndex("CommentUserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentPostId = 1,
                            CommentUserId = 1,
                            Content = "Hippity hoppity",
                            PostedAt = new DateTime(2019, 6, 25, 2, 49, 8, 849, DateTimeKind.Local).AddTicks(3658)
                        });
                });

            modelBuilder.Entity("Angular.Models.Following", b =>
                {
                    b.Property<int>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FollowingTargetUserId");

                    b.Property<int?>("FollowingUserId");

                    b.HasKey("FollowId");

                    b.HasIndex("FollowingTargetUserId");

                    b.HasIndex("FollowingUserId");

                    b.ToTable("Followings");
                });

            modelBuilder.Entity("Angular.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GuestInvitationId");

                    b.Property<int>("GuestUserId");

                    b.Property<int>("InvitationId");

                    b.HasKey("GuestId");

                    b.HasIndex("GuestInvitationId");

                    b.HasIndex("GuestUserId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Angular.Models.Invitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InvitationPostId");

                    b.Property<int>("NumberOfGuest");

                    b.Property<DateTime>("Time");

                    b.Property<string>("Type");

                    b.HasKey("InvitationId");

                    b.HasIndex("InvitationPostId");

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            InvitationId = 1,
                            InvitationPostId = 1,
                            NumberOfGuest = 1,
                            Time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Angular.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LocationInvitationId");

                    b.Property<IPoint>("LocationPoint");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationInvitationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationInvitationId = 1,
                            LocationPoint = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-122.333056 47.609722)")
                        });
                });

            modelBuilder.Entity("Angular.Models.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MediaPostId");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediaId");

                    b.HasIndex("MediaPostId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Angular.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message");

                    b.Property<int>("PostUserId");

                    b.Property<DateTime>("PostedAt");

                    b.HasKey("PostId");

                    b.HasIndex("PostUserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Message = "Kaas",
                            PostUserId = 1,
                            PostedAt = new DateTime(2019, 6, 25, 2, 49, 8, 849, DateTimeKind.Local).AddTicks(459)
                        });
                });

            modelBuilder.Entity("Angular.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Rating");

                    b.Property<int>("ReviewTargetId");

                    b.Property<int>("ReviewUserId");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReviewTargetId");

                    b.HasIndex("ReviewUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Angular.Models.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BirthDate");

                    b.Property<string>("City");

                    b.Property<string>("Firstname");

                    b.Property<string>("Gender");

                    b.Property<string>("Lastname");

                    b.Property<int>("Number");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProfileDescription");

                    b.Property<string>("ProfilePicture");

                    b.Property<string>("Street");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipCode");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BirthDate = new DateTime(2019, 6, 25, 2, 49, 8, 847, DateTimeKind.Local).AddTicks(1479),
                            City = "Stadskanaal",
                            Firstname = "Jans",
                            Gender = "M",
                            Lastname = "Jansen",
                            Number = 611992103,
                            Password = "6sNsu+pxGtzIoQmNHq2nX5KFbemuNM10tzdUuL5E8Zo=.xygrNhDB6A8KLH8QilMWkw==",
                            ProfileDescription = "Kaas",
                            ProfilePicture = "Putin.jpg",
                            Street = "Hoofdkade",
                            Username = "Test",
                            ZipCode = "9503HH"
                        });
                });

            modelBuilder.Entity("Angular.Models.Comment", b =>
                {
                    b.HasOne("Angular.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("CommentPostId");

                    b.HasOne("Angular.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("CommentUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Angular.Models.Following", b =>
                {
                    b.HasOne("Angular.Models.UserAccount", "Target")
                        .WithMany()
                        .HasForeignKey("FollowingTargetUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Angular.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("FollowingUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Angular.Models.Guest", b =>
                {
                    b.HasOne("Angular.Models.Invitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("GuestInvitationId");

                    b.HasOne("Angular.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Angular.Models.Invitation", b =>
                {
                    b.HasOne("Angular.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("InvitationPostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Angular.Models.Location", b =>
                {
                    b.HasOne("Angular.Models.Invitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("LocationInvitationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Angular.Models.Media", b =>
                {
                    b.HasOne("Angular.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("MediaPostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Angular.Models.Post", b =>
                {
                    b.HasOne("Angular.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("PostUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Angular.Models.Review", b =>
                {
                    b.HasOne("Angular.Models.UserAccount", "Target")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewTargetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Angular.Models.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("ReviewUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
